// entrypoints/popup/Settings.tsx
import { StoreInfo } from './types';
import StorefrontPassword from './settings/StorefrontPassword';

interface SettingsProps {
  storeInfo: StoreInfo;
}

export default function Settings({ storeInfo }: SettingsProps) {
  return (
    <div className="flex flex-col">
      <StorefrontPassword storeInfo={storeInfo} />
    </div>
  );
}

// entrypoints/popup/Settings.svelte
<script lang="ts">
  import type { StoreInfo } from './types';
  import StorefrontPassword from './settings/StorefrontPassword.svelte';

  let { storeInfo }: { storeInfo: StoreInfo } = $props();
</script>

<div class="settings-wrapper">
  <StorefrontPassword {storeInfo} />
</div>

<style>
  .settings-wrapper {
    display: flex;
    flex-direction: column;
  }
</style>
