// entrypoints/options/components/pages/Settings.tsx
import { PageHeader } from '../PageHeader';
import { ThemeInspectorSetting } from '../settings/ThemeInspectorSettings';
import { CustomizerResizersSetting } from '../settings/CustomizerResizersSettings';
import { ShortcutsSetting } from '../settings/ShortcutsSettings';
import { AppStoreSettings } from '../settings/AppStoreSettings';
import { CollaboratorAccessSetting } from '../settings/CollaboratorAccessSettings';
import { AdminSettings } from '../settings/AdminSettings';
import { StorefrontPasswordSettings } from '../settings/StorefrontPasswordSettings';
import { GeneralSettings } from '../settings/GeneralSettings';

export function Settings() {
  return (
    <form id="settings">
      <s-grid gap="base">
        <PageHeader title="Settings" icon="settings" />
        <GeneralSettings />
        <ShortcutsSetting />
        <CollaboratorAccessSetting />
        <AdminSettings />
        <AppStoreSettings />
        <StorefrontPasswordSettings />
        <CustomizerResizersSetting />
        <ThemeInspectorSetting />
        {/* Add more setting components here as needed */}
      </s-grid>
    </form>
  );
}

// entrypoints/options/components/pages/Settings.svelte
<script lang="ts">
  import PageHeader from '../PageHeader.svelte';
  import ThemeInspectorSettings from '../settings/ThemeInspectorSettings.svelte';
  import CustomizerResizersSettings from '../settings/CustomizerResizersSettings.svelte';
  import ShortcutsSettings from '../settings/ShortcutsSettings.svelte';
  import AppStoreSettings from '../settings/AppStoreSettings.svelte';
  import CollaboratorAccessSettings from '../settings/CollaboratorAccessSettings.svelte';
  import AdminSettings from '../settings/AdminSettings.svelte';
  import StorefrontPasswordSettings from '../settings/StorefrontPasswordSettings.svelte';
  import GeneralSettings from '../settings/GeneralSettings.svelte';
</script>

<form id="settings">
  <s-grid gap="base">
    <PageHeader title="Settings" icon="settings" />
    <GeneralSettings />
    <ShortcutsSettings />
    <CollaboratorAccessSettings />
    <AdminSettings />
    <AppStoreSettings />
    <StorefrontPasswordSettings />
    <CustomizerResizersSettings />
    <ThemeInspectorSettings />
  </s-grid>
</form>
