// entrypoints/options/components/Settings.tsx
import { PageHeader } from './PageHeader';
import { ThemeInspectorSetting } from './settings/ThemeInspectorSetting';
import { CustomizerResizersSetting } from './settings/CustomizerResizersSetting';
import { ShortcutsSetting } from './settings/ShortcutsSetting';
import { AppStoreSettings } from './settings/AppStoreSettings';
import { CollaboratorAccessSetting } from './settings/CollaboratorAccessSetting';
import { AdminSettings } from './settings/AdminSettings';

export function Settings() {
  return (
    <form id="settings">
      <s-grid gap="base">
        <PageHeader title="Settings" icon="settings" />
        <ShortcutsSetting />
        <CollaboratorAccessSetting />
        <AdminSettings />
        <AppStoreSettings />
        <CustomizerResizersSetting />
        <ThemeInspectorSetting />
        {/* Add more setting components here as needed */}
      </s-grid>
    </form>
  );
}

// entrypoints/options/components/pages/Settings.svelte
<script lang="ts">
  import PageHeader from '../PageHeader.svelte';
  import ThemeInspectorSettings from '../settings/ThemeInspectorSettings.svelte';
  import CustomizerResizersSettings from '../settings/CustomizerResizersSettings.svelte';
  import ShortcutsSettings from '../settings/ShortcutsSettings.svelte';
  import AppStoreSettings from '../settings/AppStoreSettings.svelte';
  import CollaboratorAccessSettings from '../settings/CollaboratorAccessSettings.svelte';
  import AdminSettings from '../settings/AdminSettings.svelte';
  import StorefrontPasswordSettings from '../settings/StorefrontPasswordSettings.svelte';
  import GeneralSettings from '../settings/GeneralSettings.svelte';
</script>

<form id="settings">
  <s-grid gap="base">
    <PageHeader title="Settings" icon="settings" />
    <GeneralSettings />
    <ShortcutsSettings />
    <CollaboratorAccessSettings />
    <AdminSettings />
    <AppStoreSettings />
    <StorefrontPasswordSettings />
    <CustomizerResizersSettings />
    <ThemeInspectorSettings />
  </s-grid>
</form>
