// entrypoints/options/components/settings/AdminSettings.tsx
import { useEffect, useContext } from 'preact/hooks';
import { SettingsContext } from '../../contexts/SettingsContext';
import { setCheckboxValue, onCheckboxChange } from '~/utils/polaris.polyfill';

interface SettingItem {
  key: string;
  label: string;
  details?: string;
  subSettings?: SettingItem[];
}

const settingsItems: SettingItem[] = [
  {
    key: 'collapsibleSidebar',
    label: 'Collapsible sidebar',
    details: 'Adds a toggle button to collapse/expand the Shopify admin navigation sidebar'
  },
  {
    key: 'warnBeforeClosingCodeEditor',
    label: 'Warn before closing code editor',
    details: 'Show a confirmation dialog before closing the theme code editor page'
  },
  {
    key: 'themeListUtils',
    label: 'Theme list utilities',
    details: 'Adds copy buttons for Theme ID and Preview URL to each theme on the themes list page'
  }
];

export function AdminSettings() {
  const context = useContext(SettingsContext);
  if (!context) throw new Error('AdminSettings must be used within SettingsProvider');
  const { settings, updateSettings, isLoading } = context;

  const initializeCheckboxes = (items: SettingItem[], prefix = 'admin') => {
    items.forEach(({ key, subSettings }) => {
      // Set initial value
      setCheckboxValue(`${prefix}-${key}`, settings.admin?.[key as keyof typeof settings.admin] ?? false);

      // Initialize sub-settings if they exist
      if (subSettings && subSettings.length > 0) {
        initializeCheckboxes(subSettings, `${prefix}-${key}`);
      }
    });
  };

  const setupListeners = (items: SettingItem[], prefix = 'admin'): (() => void)[] => {
    const cleanupFunctions: (() => void)[] = [];

    items.forEach(({ key, subSettings }) => {
      const cleanup = onCheckboxChange(`${prefix}-${key}`, async (checked) => {
        await updateSettings({
          admin: {
            ...settings.admin,
            [key]: checked
          }
        });

        // If unchecking parent, also uncheck sub-settings
        if (!checked && subSettings && subSettings.length > 0) {
          subSettings.forEach((sub) => {
            setCheckboxValue(`${prefix}-${key}-${sub.key}`, false);
          });
        }
      });

      if (cleanup) cleanupFunctions.push(cleanup);

      // Setup listeners for sub-settings
      if (subSettings && subSettings.length > 0) {
        cleanupFunctions.push(...setupListeners(subSettings, `${prefix}-${key}`));
      }
    });

    return cleanupFunctions;
  };

  useEffect(() => {
    if (isLoading) return;
    initializeCheckboxes(settingsItems);
  }, [isLoading, settings.admin]);

  useEffect(() => {
    if (isLoading) return;

    const cleanupFunctions = setupListeners(settingsItems);

    return () => {
      cleanupFunctions.forEach((fn) => fn());
    };
  }, [isLoading, settings.admin, updateSettings]);

  const renderSettings = (items: SettingItem[], prefix = 'admin', depth = 0) => {
    return items.map(({ key, label, details, subSettings }) => {
      const parentEnabled = depth === 0 || settings.admin?.[key as keyof typeof settings.admin];
      const hasSubSettings = subSettings && subSettings.length > 0;

      return (
        <>
          <div style={{ marginLeft: `${depth * 24}px` }} key={`${prefix}-${key}`}>
            <s-checkbox name={`${prefix}-${key}`} label={label} details={details ?? ''} />
          </div>
          {hasSubSettings && parentEnabled && (
            <div style={{ marginTop: '8px' }}>{renderSettings(subSettings, `${prefix}-${key}`, depth + 1)}</div>
          )}
        </>
      );
    });
  };

  return (
    <s-section heading="Shopify Admin">
      <s-paragraph>Customize the Shopify admin dashboard.</s-paragraph>
      <s-grid gap="small">{renderSettings(settingsItems)}</s-grid>
    </s-section>
  );
}

// entrypoints/options/components/settings/AdminSettings.svelte
<script lang="ts">
  import { getSettingsStore } from '../../stores/settings.svelte';

  const store = getSettingsStore();

  interface SettingItem {
    key: string;
    label: string;
    details?: string;
    subSettings?: SettingItem[];
  }

  const settingsItems: SettingItem[] = [
    { key: 'collapsibleSidebar', label: 'Collapsible sidebar', details: 'Adds a toggle button to collapse/expand the Shopify admin navigation sidebar' },
    { key: 'warnBeforeClosingCodeEditor', label: 'Warn before closing code editor', details: 'Show a confirmation dialog before closing the theme code editor page' },
    { key: 'themeListUtils', label: 'Theme list utilities', details: 'Adds copy buttons for Theme ID and Preview URL to each theme on the themes list page' }
  ];

  function handleChange(key: string, e: Event) {
    store.updateSettings({ admin: { ...store.settings.admin, [key]: (e.currentTarget as HTMLInputElement).checked } });
  }
</script>

{#snippet renderSettings(items: SettingItem[], depth: number)}
  {#each items as { key, label, details, subSettings }}
    <div style="margin-left: {depth * 24}px">
      <s-checkbox
        name="admin-{key}"
        {label}
        details={details ?? ''}
        checked={store.settings.admin?.[key as keyof typeof store.settings.admin] ?? false}
        onchange={(e: Event) => handleChange(key, e)}
      ></s-checkbox>
    </div>
    {#if subSettings && subSettings.length > 0 && store.settings.admin?.[key as keyof typeof store.settings.admin]}
      <div style="margin-top: 8px">
        {@render renderSettings(subSettings, depth + 1)}
      </div>
    {/if}
  {/each}
{/snippet}

<s-section heading="Shopify Admin">
  <s-paragraph>Customize the Shopify admin dashboard.</s-paragraph>
  <s-grid gap="small">
    {@render renderSettings(settingsItems, 0)}
  </s-grid>
</s-section>
